# NAME: Matthew Pombo
# EMAIL: mppombo5@gmail.com
# UID: 405140036

UID = 405140036
tarname = lab3a-$(UID).tar.gz
opts = -Wall -Wextra

# File categories
submission = Makefile README

# Targets
.PHONY: dist
dist:
	tar -cvzf $(tarname) $(submission)
