# NAME: Matthew Pombo
# EMAIL: mppombo5@gmail.com
# UID: 405140036

tarfiles = Makefile README my_beaglebone.jpg connected.png copy.png build_run.png git.png
UID=405140036

default: 
	tar -cvzf lab4a-$(UID).tar.gz $(tarfiles)

.PHONY: clean
clean:
	rm -rf lab4a-$(UID).tar.gz
